# Generated by Django 4.2.1 on 2023-06-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopanimal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
