# Generated by Django 4.2.1 on 2023-06-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopanimal', '0002_remove_categoria_id_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
