# Generated by Django 4.2.1 on 2023-06-26 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shopanimal', '0002_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Shopanimal.usuariorol'),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='id_rol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
