# Generated by Django 4.2.1 on 2023-06-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopanimal', '0003_alter_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='id_rol',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
