# Generated by Django 4.2.3 on 2023-07-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shopanimal', '0004_alter_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioRol',
            new_name='TipoUsuario',
        ),
        migrations.RenameField(
            model_name='tipousuario',
            old_name='id_rol',
            new_name='id_tipo',
        ),
        migrations.RenameField(
            model_name='tipousuario',
            old_name='rol',
            new_name='nombre_tipo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shopanimal.tipousuario'),
            preserve_default=False,
        ),
    ]
